*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 24.11.2020 at 19:27:48 by user MAZZARELLI
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZEFATT_MAP_STR_V................................*
FORM GET_DATA_ZEFATT_MAP_STR_V.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEFATT_MAP_STRUC WHERE
(VIM_WHERETAB) .
    CLEAR ZEFATT_MAP_STR_V .
ZEFATT_MAP_STR_V-MANDT =
ZEFATT_MAP_STRUC-MANDT .
ZEFATT_MAP_STR_V-INTERFACCIA =
ZEFATT_MAP_STRUC-INTERFACCIA .
ZEFATT_MAP_STR_V-REGOLA_MAP =
ZEFATT_MAP_STRUC-REGOLA_MAP .
ZEFATT_MAP_STR_V-TYPE_TARGET =
ZEFATT_MAP_STRUC-TYPE_TARGET .
ZEFATT_MAP_STR_V-TAG_XML =
ZEFATT_MAP_STRUC-TAG_XML .
<VIM_TOTAL_STRUC> = ZEFATT_MAP_STR_V.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZEFATT_MAP_STR_V .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZEFATT_MAP_STR_V.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZEFATT_MAP_STR_V-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_MAP_STRUC WHERE
  INTERFACCIA = ZEFATT_MAP_STR_V-INTERFACCIA AND
  REGOLA_MAP = ZEFATT_MAP_STR_V-REGOLA_MAP AND
  TYPE_TARGET = ZEFATT_MAP_STR_V-TYPE_TARGET .
    IF SY-SUBRC = 0.
    DELETE ZEFATT_MAP_STRUC .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_MAP_STRUC WHERE
  INTERFACCIA = ZEFATT_MAP_STR_V-INTERFACCIA AND
  REGOLA_MAP = ZEFATT_MAP_STR_V-REGOLA_MAP AND
  TYPE_TARGET = ZEFATT_MAP_STR_V-TYPE_TARGET .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEFATT_MAP_STRUC.
    ENDIF.
ZEFATT_MAP_STRUC-MANDT =
ZEFATT_MAP_STR_V-MANDT .
ZEFATT_MAP_STRUC-INTERFACCIA =
ZEFATT_MAP_STR_V-INTERFACCIA .
ZEFATT_MAP_STRUC-REGOLA_MAP =
ZEFATT_MAP_STR_V-REGOLA_MAP .
ZEFATT_MAP_STRUC-TYPE_TARGET =
ZEFATT_MAP_STR_V-TYPE_TARGET .
ZEFATT_MAP_STRUC-TAG_XML =
ZEFATT_MAP_STR_V-TAG_XML .
    IF SY-SUBRC = 0.
    UPDATE ZEFATT_MAP_STRUC .
    ELSE.
    INSERT ZEFATT_MAP_STRUC .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZEFATT_MAP_STR_V-UPD_FLAG,
STATUS_ZEFATT_MAP_STR_V-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZEFATT_MAP_STR_V.
  SELECT SINGLE * FROM ZEFATT_MAP_STRUC WHERE
INTERFACCIA = ZEFATT_MAP_STR_V-INTERFACCIA AND
REGOLA_MAP = ZEFATT_MAP_STR_V-REGOLA_MAP AND
TYPE_TARGET = ZEFATT_MAP_STR_V-TYPE_TARGET .
ZEFATT_MAP_STR_V-MANDT =
ZEFATT_MAP_STRUC-MANDT .
ZEFATT_MAP_STR_V-INTERFACCIA =
ZEFATT_MAP_STRUC-INTERFACCIA .
ZEFATT_MAP_STR_V-REGOLA_MAP =
ZEFATT_MAP_STRUC-REGOLA_MAP .
ZEFATT_MAP_STR_V-TYPE_TARGET =
ZEFATT_MAP_STRUC-TYPE_TARGET .
ZEFATT_MAP_STR_V-TAG_XML =
ZEFATT_MAP_STRUC-TAG_XML .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZEFATT_MAP_STR_V USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZEFATT_MAP_STR_V-INTERFACCIA TO
ZEFATT_MAP_STRUC-INTERFACCIA .
MOVE ZEFATT_MAP_STR_V-REGOLA_MAP TO
ZEFATT_MAP_STRUC-REGOLA_MAP .
MOVE ZEFATT_MAP_STR_V-TYPE_TARGET TO
ZEFATT_MAP_STRUC-TYPE_TARGET .
MOVE ZEFATT_MAP_STR_V-MANDT TO
ZEFATT_MAP_STRUC-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEFATT_MAP_STRUC'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEFATT_MAP_STRUC TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEFATT_MAP_STRUC'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
