*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 04.01.2021 at 18:21:47
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZEFATT_CONF_RESV................................*
FORM GET_DATA_ZEFATT_CONF_RESV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEFATT_CONF_REST WHERE
(VIM_WHERETAB) .
    CLEAR ZEFATT_CONF_RESV .
ZEFATT_CONF_RESV-MANDT =
ZEFATT_CONF_REST-MANDT .
ZEFATT_CONF_RESV-INTERFACCIA =
ZEFATT_CONF_REST-INTERFACCIA .
ZEFATT_CONF_RESV-RFC_LOGIN =
ZEFATT_CONF_REST-RFC_LOGIN .
ZEFATT_CONF_RESV-UTENTE =
ZEFATT_CONF_REST-UTENTE .
ZEFATT_CONF_RESV-PASSWORD =
ZEFATT_CONF_REST-PASSWORD .
ZEFATT_CONF_RESV-RFC_SERVICE =
ZEFATT_CONF_REST-RFC_SERVICE .
ZEFATT_CONF_RESV-ACTIVE =
ZEFATT_CONF_REST-ACTIVE .
<VIM_TOTAL_STRUC> = ZEFATT_CONF_RESV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZEFATT_CONF_RESV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZEFATT_CONF_RESV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZEFATT_CONF_RESV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_CONF_REST WHERE
  INTERFACCIA = ZEFATT_CONF_RESV-INTERFACCIA AND
  RFC_LOGIN = ZEFATT_CONF_RESV-RFC_LOGIN .
    IF SY-SUBRC = 0.
    DELETE ZEFATT_CONF_REST .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_CONF_REST WHERE
  INTERFACCIA = ZEFATT_CONF_RESV-INTERFACCIA AND
  RFC_LOGIN = ZEFATT_CONF_RESV-RFC_LOGIN .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEFATT_CONF_REST.
    ENDIF.
ZEFATT_CONF_REST-MANDT =
ZEFATT_CONF_RESV-MANDT .
ZEFATT_CONF_REST-INTERFACCIA =
ZEFATT_CONF_RESV-INTERFACCIA .
ZEFATT_CONF_REST-RFC_LOGIN =
ZEFATT_CONF_RESV-RFC_LOGIN .
ZEFATT_CONF_REST-UTENTE =
ZEFATT_CONF_RESV-UTENTE .
ZEFATT_CONF_REST-PASSWORD =
ZEFATT_CONF_RESV-PASSWORD .
ZEFATT_CONF_REST-RFC_SERVICE =
ZEFATT_CONF_RESV-RFC_SERVICE .
ZEFATT_CONF_REST-ACTIVE =
ZEFATT_CONF_RESV-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZEFATT_CONF_REST ##WARN_OK.
    ELSE.
    INSERT ZEFATT_CONF_REST .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZEFATT_CONF_RESV-UPD_FLAG,
STATUS_ZEFATT_CONF_RESV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZEFATT_CONF_RESV.
  SELECT SINGLE * FROM ZEFATT_CONF_REST WHERE
INTERFACCIA = ZEFATT_CONF_RESV-INTERFACCIA AND
RFC_LOGIN = ZEFATT_CONF_RESV-RFC_LOGIN .
ZEFATT_CONF_RESV-MANDT =
ZEFATT_CONF_REST-MANDT .
ZEFATT_CONF_RESV-INTERFACCIA =
ZEFATT_CONF_REST-INTERFACCIA .
ZEFATT_CONF_RESV-RFC_LOGIN =
ZEFATT_CONF_REST-RFC_LOGIN .
ZEFATT_CONF_RESV-UTENTE =
ZEFATT_CONF_REST-UTENTE .
ZEFATT_CONF_RESV-PASSWORD =
ZEFATT_CONF_REST-PASSWORD .
ZEFATT_CONF_RESV-RFC_SERVICE =
ZEFATT_CONF_REST-RFC_SERVICE .
ZEFATT_CONF_RESV-ACTIVE =
ZEFATT_CONF_REST-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZEFATT_CONF_RESV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZEFATT_CONF_RESV-INTERFACCIA TO
ZEFATT_CONF_REST-INTERFACCIA .
MOVE ZEFATT_CONF_RESV-RFC_LOGIN TO
ZEFATT_CONF_REST-RFC_LOGIN .
MOVE ZEFATT_CONF_RESV-MANDT TO
ZEFATT_CONF_REST-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEFATT_CONF_REST'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEFATT_CONF_REST TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEFATT_CONF_REST'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
