*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 04.01.2021 at 16:11:31
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZEFATT_CONFFILEV................................*
FORM GET_DATA_ZEFATT_CONFFILEV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEFATT_CONF_FILE WHERE
(VIM_WHERETAB) .
    CLEAR ZEFATT_CONFFILEV .
ZEFATT_CONFFILEV-MANDT =
ZEFATT_CONF_FILE-MANDT .
ZEFATT_CONFFILEV-INTERFACCIA =
ZEFATT_CONF_FILE-INTERFACCIA .
ZEFATT_CONFFILEV-BUKRS =
ZEFATT_CONF_FILE-BUKRS .
ZEFATT_CONFFILEV-PATHINTERN =
ZEFATT_CONF_FILE-PATHINTERN .
ZEFATT_CONFFILEV-BACKUP =
ZEFATT_CONF_FILE-BACKUP .
ZEFATT_CONFFILEV-DELETE_FILE =
ZEFATT_CONF_FILE-DELETE_FILE .
ZEFATT_CONFFILEV-ACTIVE =
ZEFATT_CONF_FILE-ACTIVE .
<VIM_TOTAL_STRUC> = ZEFATT_CONFFILEV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZEFATT_CONFFILEV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZEFATT_CONFFILEV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZEFATT_CONFFILEV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_CONF_FILE WHERE
  INTERFACCIA = ZEFATT_CONFFILEV-INTERFACCIA AND
  BUKRS = ZEFATT_CONFFILEV-BUKRS .
    IF SY-SUBRC = 0.
    DELETE ZEFATT_CONF_FILE .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_CONF_FILE WHERE
  INTERFACCIA = ZEFATT_CONFFILEV-INTERFACCIA AND
  BUKRS = ZEFATT_CONFFILEV-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEFATT_CONF_FILE.
    ENDIF.
ZEFATT_CONF_FILE-MANDT =
ZEFATT_CONFFILEV-MANDT .
ZEFATT_CONF_FILE-INTERFACCIA =
ZEFATT_CONFFILEV-INTERFACCIA .
ZEFATT_CONF_FILE-BUKRS =
ZEFATT_CONFFILEV-BUKRS .
ZEFATT_CONF_FILE-PATHINTERN =
ZEFATT_CONFFILEV-PATHINTERN .
ZEFATT_CONF_FILE-BACKUP =
ZEFATT_CONFFILEV-BACKUP .
ZEFATT_CONF_FILE-DELETE_FILE =
ZEFATT_CONFFILEV-DELETE_FILE .
ZEFATT_CONF_FILE-ACTIVE =
ZEFATT_CONFFILEV-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZEFATT_CONF_FILE ##WARN_OK.
    ELSE.
    INSERT ZEFATT_CONF_FILE .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZEFATT_CONFFILEV-UPD_FLAG,
STATUS_ZEFATT_CONFFILEV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZEFATT_CONFFILEV.
  SELECT SINGLE * FROM ZEFATT_CONF_FILE WHERE
INTERFACCIA = ZEFATT_CONFFILEV-INTERFACCIA AND
BUKRS = ZEFATT_CONFFILEV-BUKRS .
ZEFATT_CONFFILEV-MANDT =
ZEFATT_CONF_FILE-MANDT .
ZEFATT_CONFFILEV-INTERFACCIA =
ZEFATT_CONF_FILE-INTERFACCIA .
ZEFATT_CONFFILEV-BUKRS =
ZEFATT_CONF_FILE-BUKRS .
ZEFATT_CONFFILEV-PATHINTERN =
ZEFATT_CONF_FILE-PATHINTERN .
ZEFATT_CONFFILEV-BACKUP =
ZEFATT_CONF_FILE-BACKUP .
ZEFATT_CONFFILEV-DELETE_FILE =
ZEFATT_CONF_FILE-DELETE_FILE .
ZEFATT_CONFFILEV-ACTIVE =
ZEFATT_CONF_FILE-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZEFATT_CONFFILEV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZEFATT_CONFFILEV-INTERFACCIA TO
ZEFATT_CONF_FILE-INTERFACCIA .
MOVE ZEFATT_CONFFILEV-BUKRS TO
ZEFATT_CONF_FILE-BUKRS .
MOVE ZEFATT_CONFFILEV-MANDT TO
ZEFATT_CONF_FILE-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEFATT_CONF_FILE'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEFATT_CONF_FILE TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEFATT_CONF_FILE'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
