*---------------------------------------------------------------------*
*    view related FORM routines
*   generation date: 04.01.2021 at 16:08:41
*   view maintenance generator version: #001407#
*---------------------------------------------------------------------*
*...processing: ZEFATT_CONF_FTPV................................*
FORM GET_DATA_ZEFATT_CONF_FTPV.
  PERFORM VIM_FILL_WHERETAB.
*.read data from database.............................................*
  REFRESH TOTAL.
  CLEAR   TOTAL.
  SELECT * FROM ZEFATT_CONF_FTP WHERE
(VIM_WHERETAB) .
    CLEAR ZEFATT_CONF_FTPV .
ZEFATT_CONF_FTPV-MANDT =
ZEFATT_CONF_FTP-MANDT .
ZEFATT_CONF_FTPV-INTERFACCIA =
ZEFATT_CONF_FTP-INTERFACCIA .
ZEFATT_CONF_FTPV-BUKRS =
ZEFATT_CONF_FTP-BUKRS .
ZEFATT_CONF_FTPV-HOST =
ZEFATT_CONF_FTP-HOST .
ZEFATT_CONF_FTPV-UTENTE =
ZEFATT_CONF_FTP-UTENTE .
ZEFATT_CONF_FTPV-PASSWORD =
ZEFATT_CONF_FTP-PASSWORD .
ZEFATT_CONF_FTPV-PATH =
ZEFATT_CONF_FTP-PATH .
ZEFATT_CONF_FTPV-BACKUP =
ZEFATT_CONF_FTP-BACKUP .
ZEFATT_CONF_FTPV-DELETE_FILE =
ZEFATT_CONF_FTP-DELETE_FILE .
ZEFATT_CONF_FTPV-ACTIVE =
ZEFATT_CONF_FTP-ACTIVE .
<VIM_TOTAL_STRUC> = ZEFATT_CONF_FTPV.
    APPEND TOTAL.
  ENDSELECT.
  SORT TOTAL BY <VIM_XTOTAL_KEY>.
  <STATUS>-ALR_SORTED = 'R'.
*.check dynamic selectoptions (not in DDIC)...........................*
  IF X_HEADER-SELECTION NE SPACE.
    PERFORM CHECK_DYNAMIC_SELECT_OPTIONS.
  ELSEIF X_HEADER-DELMDTFLAG NE SPACE.
    PERFORM BUILD_MAINKEY_TAB.
  ENDIF.
  REFRESH EXTRACT.
ENDFORM.
*---------------------------------------------------------------------*
FORM DB_UPD_ZEFATT_CONF_FTPV .
*.process data base updates/inserts/deletes.........................*
LOOP AT TOTAL.
  CHECK <ACTION> NE ORIGINAL.
MOVE <VIM_TOTAL_STRUC> TO ZEFATT_CONF_FTPV.
  IF <ACTION> = UPDATE_GELOESCHT.
    <ACTION> = GELOESCHT.
  ENDIF.
  CASE <ACTION>.
   WHEN NEUER_GELOESCHT.
IF STATUS_ZEFATT_CONF_FTPV-ST_DELETE EQ GELOESCHT.
     READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
     IF SY-SUBRC EQ 0.
       DELETE EXTRACT INDEX SY-TABIX.
     ENDIF.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN GELOESCHT.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_CONF_FTP WHERE
  INTERFACCIA = ZEFATT_CONF_FTPV-INTERFACCIA AND
  BUKRS = ZEFATT_CONF_FTPV-BUKRS .
    IF SY-SUBRC = 0.
    DELETE ZEFATT_CONF_FTP .
    ENDIF.
    IF STATUS-DELETE EQ GELOESCHT.
      READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY> BINARY SEARCH.
      DELETE EXTRACT INDEX SY-TABIX.
    ENDIF.
    DELETE TOTAL.
    IF X_HEADER-DELMDTFLAG NE SPACE.
      PERFORM DELETE_FROM_MAINKEY_TAB.
    ENDIF.
   WHEN OTHERS.
  SELECT SINGLE FOR UPDATE * FROM ZEFATT_CONF_FTP WHERE
  INTERFACCIA = ZEFATT_CONF_FTPV-INTERFACCIA AND
  BUKRS = ZEFATT_CONF_FTPV-BUKRS .
    IF SY-SUBRC <> 0.   "insert preprocessing: init WA
      CLEAR ZEFATT_CONF_FTP.
    ENDIF.
ZEFATT_CONF_FTP-MANDT =
ZEFATT_CONF_FTPV-MANDT .
ZEFATT_CONF_FTP-INTERFACCIA =
ZEFATT_CONF_FTPV-INTERFACCIA .
ZEFATT_CONF_FTP-BUKRS =
ZEFATT_CONF_FTPV-BUKRS .
ZEFATT_CONF_FTP-HOST =
ZEFATT_CONF_FTPV-HOST .
ZEFATT_CONF_FTP-UTENTE =
ZEFATT_CONF_FTPV-UTENTE .
ZEFATT_CONF_FTP-PASSWORD =
ZEFATT_CONF_FTPV-PASSWORD .
ZEFATT_CONF_FTP-PATH =
ZEFATT_CONF_FTPV-PATH .
ZEFATT_CONF_FTP-BACKUP =
ZEFATT_CONF_FTPV-BACKUP .
ZEFATT_CONF_FTP-DELETE_FILE =
ZEFATT_CONF_FTPV-DELETE_FILE .
ZEFATT_CONF_FTP-ACTIVE =
ZEFATT_CONF_FTPV-ACTIVE .
    IF SY-SUBRC = 0.
    UPDATE ZEFATT_CONF_FTP ##WARN_OK.
    ELSE.
    INSERT ZEFATT_CONF_FTP .
    ENDIF.
    READ TABLE EXTRACT WITH KEY <VIM_XTOTAL_KEY>.
    IF SY-SUBRC EQ 0.
      <XACT> = ORIGINAL.
      MODIFY EXTRACT INDEX SY-TABIX.
    ENDIF.
    <ACTION> = ORIGINAL.
    MODIFY TOTAL.
  ENDCASE.
ENDLOOP.
CLEAR: STATUS_ZEFATT_CONF_FTPV-UPD_FLAG,
STATUS_ZEFATT_CONF_FTPV-UPD_CHECKD.
MESSAGE S018(SV).
ENDFORM.
*---------------------------------------------------------------------*
FORM READ_SINGLE_ZEFATT_CONF_FTPV.
  SELECT SINGLE * FROM ZEFATT_CONF_FTP WHERE
INTERFACCIA = ZEFATT_CONF_FTPV-INTERFACCIA AND
BUKRS = ZEFATT_CONF_FTPV-BUKRS .
ZEFATT_CONF_FTPV-MANDT =
ZEFATT_CONF_FTP-MANDT .
ZEFATT_CONF_FTPV-INTERFACCIA =
ZEFATT_CONF_FTP-INTERFACCIA .
ZEFATT_CONF_FTPV-BUKRS =
ZEFATT_CONF_FTP-BUKRS .
ZEFATT_CONF_FTPV-HOST =
ZEFATT_CONF_FTP-HOST .
ZEFATT_CONF_FTPV-UTENTE =
ZEFATT_CONF_FTP-UTENTE .
ZEFATT_CONF_FTPV-PASSWORD =
ZEFATT_CONF_FTP-PASSWORD .
ZEFATT_CONF_FTPV-PATH =
ZEFATT_CONF_FTP-PATH .
ZEFATT_CONF_FTPV-BACKUP =
ZEFATT_CONF_FTP-BACKUP .
ZEFATT_CONF_FTPV-DELETE_FILE =
ZEFATT_CONF_FTP-DELETE_FILE .
ZEFATT_CONF_FTPV-ACTIVE =
ZEFATT_CONF_FTP-ACTIVE .
ENDFORM.
*---------------------------------------------------------------------*
FORM CORR_MAINT_ZEFATT_CONF_FTPV USING VALUE(CM_ACTION) RC.
  DATA: RETCODE LIKE SY-SUBRC, COUNT TYPE I, TRSP_KEYLEN TYPE SYFLENG.
  FIELD-SYMBOLS: <TAB_KEY_X> TYPE X.
  CLEAR RC.
MOVE ZEFATT_CONF_FTPV-INTERFACCIA TO
ZEFATT_CONF_FTP-INTERFACCIA .
MOVE ZEFATT_CONF_FTPV-BUKRS TO
ZEFATT_CONF_FTP-BUKRS .
MOVE ZEFATT_CONF_FTPV-MANDT TO
ZEFATT_CONF_FTP-MANDT .
  CORR_KEYTAB             =  E071K.
  CORR_KEYTAB-OBJNAME     = 'ZEFATT_CONF_FTP'.
  IF NOT <vim_corr_keyx> IS ASSIGNED.
    ASSIGN CORR_KEYTAB-TABKEY TO <vim_corr_keyx> CASTING.
  ENDIF.
  ASSIGN ZEFATT_CONF_FTP TO <TAB_KEY_X> CASTING.
  PERFORM VIM_GET_TRSPKEYLEN
    USING 'ZEFATT_CONF_FTP'
    CHANGING TRSP_KEYLEN.
  <VIM_CORR_KEYX>(TRSP_KEYLEN) = <TAB_KEY_X>(TRSP_KEYLEN).
  PERFORM UPDATE_CORR_KEYTAB USING CM_ACTION RETCODE.
  ADD: RETCODE TO RC, 1 TO COUNT.
  IF RC LT COUNT AND CM_ACTION NE PRUEFEN.
    CLEAR RC.
  ENDIF.

ENDFORM.
*---------------------------------------------------------------------*
