*"* components of interface ZIF_FATT_BADI_SOLUZIONE
interface ZIF_FATT_BADI_SOLUZIONE
  public .


  interfaces IF_BADI_INTERFACE .

  methods HANDLE_MAPPING
    importing
      !INTERFACCIA type ZEFATT_INTERFACCIA
    exporting
      !DDT type ZEFATT_DDT_MAP_T
      !INTEST_SOCIETA type ZEFATT_INTEST_MAP
      !INTEST_FORNITORE type ZEFATT_INTEST_FOR_MAP
      !HEADER type ZEFATT_HEADER_MAP_T
      !ITEM type ZEFATT_ITEM_MAP_T
      !ODA type ZEFATT_ODA_MAP_T
      !ALLEGATI type ZEFATT_ATTACH_MAP_T
      !RITENUTA type ZEFATT_RITENUTA_MAP_T
      !CASSA type ZEFATT_CASSA_MAP_T
      !MESSAGE type BAPIRET2-MESSAGE
      !TRASMISSIONE type ZEFATT_INTEST_TRASMISSIONE
      !NOTIFICA type ZFATT_NOTIF_MAP
    changing
      !XML type XSTRING .
  methods HANDLE_SOLUZIONE
    importing
      !INTERFACCIA type ZEFATT_INTERFACCIA
      !DDT type ZEFATT_DDT_MAP_T
      !INTEST_SOCIETA type ZEFATT_INTEST_MAP
      !INTEST_FORNITORE type ZEFATT_INTEST_FOR_MAP
      !HEADER type ZEFATT_HEADER_MAP_T
      !ITEM type ZEFATT_ITEM_MAP_T
      !ODA type ZEFATT_ODA_MAP_T
      !ALLEGATI type ZEFATT_ATTACH_MAP_T
      !RITENUTA type ZEFATT_RITENUTA_MAP_T
      !CASSA type ZEFATT_CASSA_MAP_T
      !MESSAGE type BAPIRET2-MESSAGE
      !TRASMISSIONE type ZEFATT_INTEST_TRASMISSIONE
      !NOTIFICA type ZFATT_NOTIF_MAP
      !FILE_NAME type STRING .
endinterface.
